In [1]:
import pandas as pd

In [2]:
# Excel-Dateien einlesen und DF erstellen
merged_dataset = pd.read_excel('merged_dataset.xlsx')
tweets_cleaned = pd.read_excel('tweets_cleaned.xlsx')
tweets_cleaned_aggr = pd.read_csv('tweets_cleaned_aggr.csv')

In [3]:
#Blick in die Hotel-Daten
merged_dataset

,Unnamed: 0,date_crawl,city,uid,book_date,price,event,rating,provider,source
0,0,2023-03-30,La Palma,title_44546103,2023-05-20,90,True,4.780000,privat,airbnb
1,1,2023-03-30,La Palma,title_14832235,2023-05-20,86,True,4.780000,privat,airbnb
2,2,2023-03-30,La Palma,title_22183776,2023-05-20,63,True,4.900000,privat,airbnb
3,3,2023-03-30,La Palma,title_26944967,2023-05-20,109,True,4.760000,privat,airbnb
4,4,2023-03-30,La Palma,title_741718109680848267,2023-05-20,46,True,4.850000,privat,airbnb
...,...,...,...,...,...,...,...,...,...,...
202919,97484,2023-04-15,Halle,https://www.booking.com/hotel/us/augusta-civic...,2023-06-23,201,False,3.400000,gewerblich,booking
202920,97485,2023-04-15,Halle,https://www.booking.com/hotel/us/fairfield-inn...,2023-06-23,213,False,4.050000,gewerblich,booking
202921,97486,2023-04-15,Halle,https://www.booking.com/hotel/us/augusta-281-c...,2023-06-23,201,False,3.500000,gewerblich,booking
202922,97489,2023-04-15,Halle,https://www.booking.com/hotel/us/charming-wate...,2023-06-23,767,False,3.997292,privat,booking
202923,97490,2023-04-15,Halle,https://www.booking.com/hotel/us/clary-lake-be...,2023-06-23,101,False,4.700000,gewerblich,booking

In [4]:
#Blick in die Twitter-Daten
tweets_cleaned

         city           event_name  tweets  retweets  likes  replies
0    La Palma                MLF23      18         8     68        1
1   Barcelona                BBF23      12        27     71        0
2        Lyon              NS20ans       1         1      3        0
3    Bruessel               lbjw23       0         0      0        0
4    Muenchen        FrÃ¼hlingsfest      45         9    106       15
5   Amsterdam             kingsday      29        21    127       16
6     Sevilla         FeriadeAbril     303       977   2770      154
7    Helsinki            apriljazz       4         2     12        0
8    Brighton      FoodiesFestival       1         1      4        0
9     Hamburg      hafengeburtstag       9        29     90        8
10     Berlin  Karnevalderkulturen       0         0      0        0
11     Monaco             MonacoGP     129       992  11436      237
12  Noordwijk         bloemencorso      15         2      5        0
13    Bologna              ImolaGP      67       189   2637       85
14      Halle       HÃ¤ndelFestival       0         0      0        0

In [5]:
#Blick in die aggregierten Twitter-Daten
tweets_cleaned_aggr

,hashtag,date,retweets,likes,replies,retweets_cum,likes_cum,replies_cum
0,BBF23,2023-03-30,17,40,0,17,40,0
1,BBF23,2023-03-31,2,6,0,19,46,0
2,BBF23,2023-04-04,0,1,0,19,47,0
3,BBF23,2023-04-05,0,0,0,19,47,0
4,BBF23,2023-04-05,0,0,0,19,47,0
...,...,...,...,...,...,...,...,...
628,kingsday,2023-04-14,3,29,0,20,122,12
629,kingsday,2023-04-15,0,1,0,20,123,12
630,kingsday,2023-04-15,0,0,1,20,123,13
631,kingsday,2023-04-15,0,0,0,20,123,13
632,kingsday,2023-04-15,1,4,3,21,127,16

In [6]:
# leere Spalten fÃ¼r die Twitter-Elemente zum 'merged_dataset' DF hinzufÃ¼gen
merged_dataset['event_name'] = None
merged_dataset['tweets'] = None
merged_dataset['retweets'] = None
merged_dataset['likes'] = None
merged_dataset['replies'] = None

In [7]:
#Blick in die Daten
merged_dataset

,Unnamed: 0,date_crawl,city,uid,book_date,price,event,rating,provider,source,event_name,tweets,retweets,likes,replies
0,0,2023-03-30,La Palma,title_44546103,2023-05-20,90,True,4.780000,privat,airbnb,None,None,None,None,None
1,1,2023-03-30,La Palma,title_14832235,2023-05-20,86,True,4.780000,privat,airbnb,None,None,None,None,None
2,2,2023-03-30,La Palma,title_22183776,2023-05-20,63,True,4.900000,privat,airbnb,None,None,None,None,None
3,3,2023-03-30,La Palma,title_26944967,2023-05-20,109,True,4.760000,privat,airbnb,None,None,None,None,None
4,4,2023-03-30,La Palma,title_741718109680848267,2023-05-20,46,True,4.850000,privat,airbnb,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202919,97484,2023-04-15,Halle,https://www.booking.com/hotel/us/augusta-civic...,2023-06-23,201,False,3.400000,gewerblich,booking,None,None,None,None,None
202920,97485,2023-04-15,Halle,https://www.booking.com/hotel/us/fairfield-inn...,2023-06-23,213,False,4.050000,gewerblich,booking,None,None,None,None,None
202921,97486,2023-04-15,Halle,https://www.booking.com/hotel/us/augusta-281-c...,2023-06-23,201,False,3.500000,gewerblich,booking,None,None,None,None,None
202922,97489,2023-04-15,Halle,https://www.booking.com/hotel/us/charming-wate...,2023-06-23,767,False,3.997292,privat,booking,None,None,None,None,None
202923,97490,2023-04-15,Halle,https://www.booking.com/hotel/us/clary-lake-be...,2023-06-23,101,False,4.700000,gewerblich,booking,None,None,None,None,None

In [8]:
# Die DataFrames basierend auf der 'city'-Spalte kombinieren, sodass in den neu hinzugefÃ¼gten Spalten, die gleichen Werte fÃ¼r jede Stadt stehen
# Dies wird fÃ¼r alle StÃ¤dte wiederholt
combined_df = merged_dataset.copy()
for index, row in tweets_cleaned.iterrows():
    city = row['city']
    mask = combined_df['city'] == city
    combined_df.loc[mask, 'event_name'] = row['event_name']
    combined_df.loc[mask, 'tweets'] = row['tweets']
    combined_df.loc[mask, 'retweets'] = row['retweets']
    combined_df.loc[mask, 'likes'] = row['likes']
    combined_df.loc[mask, 'replies'] = row['replies']

In [9]:
#Blick in die Daten
combined_df

,Unnamed: 0,date_crawl,city,uid,book_date,price,event,rating,provider,source,event_name,tweets,retweets,likes,replies
0,0,2023-03-30,La Palma,title_44546103,2023-05-20,90,True,4.780000,privat,airbnb,MLF23,18,8,68,1
1,1,2023-03-30,La Palma,title_14832235,2023-05-20,86,True,4.780000,privat,airbnb,MLF23,18,8,68,1
2,2,2023-03-30,La Palma,title_22183776,2023-05-20,63,True,4.900000,privat,airbnb,MLF23,18,8,68,1
3,3,2023-03-30,La Palma,title_26944967,2023-05-20,109,True,4.760000,privat,airbnb,MLF23,18,8,68,1
4,4,2023-03-30,La Palma,title_741718109680848267,2023-05-20,46,True,4.850000,privat,airbnb,MLF23,18,8,68,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202919,97484,2023-04-15,Halle,https://www.booking.com/hotel/us/augusta-civic...,2023-06-23,201,False,3.400000,gewerblich,booking,HÃ¤ndelFestival,0,0,0,0
202920,97485,2023-04-15,Halle,https://www.booking.com/hotel/us/fairfield-inn...,2023-06-23,213,False,4.050000,gewerblich,booking,HÃ¤ndelFestival,0,0,0,0
202921,97486,2023-04-15,Halle,https://www.booking.com/hotel/us/augusta-281-c...,2023-06-23,201,False,3.500000,gewerblich,booking,HÃ¤ndelFestival,0,0,0,0
202922,97489,2023-04-15,Halle,https://www.booking.com/hotel/us/charming-wate...,2023-06-23,767,False,3.997292,privat,booking,HÃ¤ndelFestival,0,0,0,0
202923,97490,2023-04-15,Halle,https://www.booking.com/hotel/us/clary-lake-be...,2023-06-23,101,False,4.700000,gewerblich,booking,HÃ¤ndelFestival,0,0,0,0

In [10]:
# 4 neue Spalten mit Social Media Analytics Kennzahlen und der jewewiligen Berechnung erstellen
# Es wird nebenbei sichergestellt, dass kein Teilen durch Null oder None auftritt.
combined_df['amplification_rate'] = combined_df.apply(lambda row: row['retweets'] / row['tweets'] if row['tweets'] != 0 and row['tweets'] is not None else 0, axis=1)
combined_df['conversation_rate'] = combined_df.apply(lambda row: row['replies'] / row['tweets'] if row['tweets'] != 0 and row['tweets'] is not None else 0, axis=1)
combined_df['applause_rate'] = combined_df.apply(lambda row: row['likes'] / row['tweets'] if row['tweets'] != 0 and row['tweets'] is not None else 0, axis=1)
combined_df['total_engagement'] = combined_df['likes'] + combined_df['tweets'] + combined_df['replies'] + combined_df['retweets']

In [11]:
#Blick in die Daten
combined_df

,Unnamed: 0,date_crawl,city,uid,book_date,price,event,rating,provider,source,event_name,tweets,retweets,likes,replies,amplification_rate,conversation_rate,applause_rate,total_engagement
0,0,2023-03-30,La Palma,title_44546103,2023-05-20,90,True,4.780000,privat,airbnb,MLF23,18,8,68,1,0.444444,0.055556,3.777778,95
1,1,2023-03-30,La Palma,title_14832235,2023-05-20,86,True,4.780000,privat,airbnb,MLF23,18,8,68,1,0.444444,0.055556,3.777778,95
2,2,2023-03-30,La Palma,title_22183776,2023-05-20,63,True,4.900000,privat,airbnb,MLF23,18,8,68,1,0.444444,0.055556,3.777778,95
3,3,2023-03-30,La Palma,title_26944967,2023-05-20,109,True,4.760000,privat,airbnb,MLF23,18,8,68,1,0.444444,0.055556,3.777778,95
4,4,2023-03-30,La Palma,title_741718109680848267,2023-05-20,46,True,4.850000,privat,airbnb,MLF23,18,8,68,1,0.444444,0.055556,3.777778,95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202919,97484,2023-04-15,Halle,https://www.booking.com/hotel/us/augusta-civic...,2023-06-23,201,False,3.400000,gewerblich,booking,HÃ¤ndelFestival,0,0,0,0,0.000000,0.000000,0.000000,0
202920,97485,2023-04-15,Halle,https://www.booking.com/hotel/us/fairfield-inn...,2023-06-23,213,False,4.050000,gewerblich,booking,HÃ¤ndelFestival,0,0,0,0,0.000000,0.000000,0.000000,0
202921,97486,2023-04-15,Halle,https://www.booking.com/hotel/us/augusta-281-c...,2023-06-23,201,False,3.500000,gewerblich,booking,HÃ¤ndelFestival,0,0,0,0,0.000000,0.000000,0.000000,0
202922,97489,2023-04-15,Halle,https://www.booking.com/hotel/us/charming-wate...,2023-06-23,767,False,3.997292,privat,booking,HÃ¤ndelFestival,0,0,0,0,0.000000,0.000000,0.000000,0
202923,97490,2023-04-15,Halle,https://www.booking.com/hotel/us/clary-lake-be...,2023-06-23,101,False,4.700000,gewerblich,booking,HÃ¤ndelFestival,0,0,0,0,0.000000,0.000000,0.000000,0

In [12]:
# Basierend auf Berechnungen der Quantile in der Excel-Datei zu den Events, haben wir 4 Kategorien erstellt und die StÃ¤dte entsprechend ihrer "Relevanz" (oder Einfluss) eingeteil
# Eine Funktion get_relevance wird erstellt, welche diese Einteilung vornimmt. Im Anschluss wird diese auf das DF angewandt
def get_relevance(city):
    if city in ["Barcelona", "Muenchen", "La Palma"]:
        return "gering"
    elif city in ["Lyon", "Halle", "Bologna", "Helsinki", "Bruessel", "Sevilla"]:
        return "mittel"
    elif city in ["Berlin", "Brighton", "Hamburg"]:
        return "hoch"
    elif city in ["Amsterdam", "Monaco", "Noordwijk"]:
        return "sehr hoch"
    else:
        return "nicht definiert"

combined_df["relevance"] = combined_df["city"].apply(get_relevance)

In [13]:
#Blick in die Daten
combined_df

,Unnamed: 0,date_crawl,city,uid,book_date,price,event,rating,provider,source,event_name,tweets,retweets,likes,replies,amplification_rate,conversation_rate,applause_rate,total_engagement,relevance
0,0,2023-03-30,La Palma,title_44546103,2023-05-20,90,True,4.780000,privat,airbnb,MLF23,18,8,68,1,0.444444,0.055556,3.777778,95,gering
1,1,2023-03-30,La Palma,title_14832235,2023-05-20,86,True,4.780000,privat,airbnb,MLF23,18,8,68,1,0.444444,0.055556,3.777778,95,gering
2,2,2023-03-30,La Palma,title_22183776,2023-05-20,63,True,4.900000,privat,airbnb,MLF23,18,8,68,1,0.444444,0.055556,3.777778,95,gering
3,3,2023-03-30,La Palma,title_26944967,2023-05-20,109,True,4.760000,privat,airbnb,MLF23,18,8,68,1,0.444444,0.055556,3.777778,95,gering
4,4,2023-03-30,La Palma,title_741718109680848267,2023-05-20,46,True,4.850000,privat,airbnb,MLF23,18,8,68,1,0.444444,0.055556,3.777778,95,gering
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202919,97484,2023-04-15,Halle,https://www.booking.com/hotel/us/augusta-civic...,2023-06-23,201,False,3.400000,gewerblich,booking,HÃ¤ndelFestival,0,0,0,0,0.000000,0.000000,0.000000,0,mittel
202920,97485,2023-04-15,Halle,https://www.booking.com/hotel/us/fairfield-inn...,2023-06-23,213,False,4.050000,gewerblich,booking,HÃ¤ndelFestival,0,0,0,0,0.000000,0.000000,0.000000,0,mittel
202921,97486,2023-04-15,Halle,https://www.booking.com/hotel/us/augusta-281-c...,2023-06-23,201,False,3.500000,gewerblich,booking,HÃ¤ndelFestival,0,0,0,0,0.000000,0.000000,0.000000,0,mittel
202922,97489,2023-04-15,Halle,https://www.booking.com/hotel/us/charming-wate...,2023-06-23,767,False,3.997292,privat,booking,HÃ¤ndelFestival,0,0,0,0,0.000000,0.000000,0.000000,0,mittel
202923,97490,2023-04-15,Halle,https://www.booking.com/hotel/us/clary-lake-be...,2023-06-23,101,False,4.700000,gewerblich,booking,HÃ¤ndelFestival,0,0,0,0,0.000000,0.000000,0.000000,0,mittel

In [14]:
# Neue Spalten in combined_df erstellen und mit None initialisieren
combined_df[['retweets_cum', 'likes_cum', 'replies_cum', 'retweets_cont', 'likes_cont', 'replies_cont']] = None

# Die Dataframes "tweets_cleaned_aggr" und "combined_df" kombinieren
for index, row in tweets_cleaned_aggr.iterrows():
    date_condition = combined_df['date_crawl'] == row['date']
    hashtag_condition = combined_df['event_name'] == row['hashtag']
    
    combined_df.loc[date_condition & hashtag_condition, ['retweets_cum', 'likes_cum', 'replies_cum', 'retweets_cont', 'likes_cont', 'replies_cont']] = row[['retweets_cum', 'likes_cum', 'replies_cum', 'retweets', 'likes', 'replies']].values

In [15]:
# Blick in den neuen DF
combined_df

,Unnamed: 0,date_crawl,city,uid,book_date,price,event,rating,provider,source,...,conversation_rate,applause_rate,total_engagement,relevance,retweets_cum,likes_cum,replies_cum,retweets_cont,likes_cont,replies_cont
0,0,2023-03-30,La Palma,title_44546103,2023-05-20,90,True,4.780000,privat,airbnb,...,0.055556,3.777778,95,gering,2,17,0,0,3,0
1,1,2023-03-30,La Palma,title_14832235,2023-05-20,86,True,4.780000,privat,airbnb,...,0.055556,3.777778,95,gering,2,17,0,0,3,0
2,2,2023-03-30,La Palma,title_22183776,2023-05-20,63,True,4.900000,privat,airbnb,...,0.055556,3.777778,95,gering,2,17,0,0,3,0
3,3,2023-03-30,La Palma,title_26944967,2023-05-20,109,True,4.760000,privat,airbnb,...,0.055556,3.777778,95,gering,2,17,0,0,3,0
4,4,2023-03-30,La Palma,title_741718109680848267,2023-05-20,46,True,4.850000,privat,airbnb,...,0.055556,3.777778,95,gering,2,17,0,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202919,97484,2023-04-15,Halle,https://www.booking.com/hotel/us/augusta-civic...,2023-06-23,201,False,3.400000,gewerblich,booking,...,0.000000,0.000000,0,mittel,None,None,None,None,None,None
202920,97485,2023-04-15,Halle,https://www.booking.com/hotel/us/fairfield-inn...,2023-06-23,213,False,4.050000,gewerblich,booking,...,0.000000,0.000000,0,mittel,None,None,None,None,None,None
202921,97486,2023-04-15,Halle,https://www.booking.com/hotel/us/augusta-281-c...,2023-06-23,201,False,3.500000,gewerblich,booking,...,0.000000,0.000000,0,mittel,None,None,None,None,None,None
202922,97489,2023-04-15,Halle,https://www.booking.com/hotel/us/charming-wate...,2023-06-23,767,False,3.997292,privat,booking,...,0.000000,0.000000,0,mittel,None,None,None,None,None,None
202923,97490,2023-04-15,Halle,https://www.booking.com/hotel/us/clary-lake-be...,2023-06-23,101,False,4.700000,gewerblich,booking,...,0.000000,0.000000,0,mittel,None,None,None,None,None,None

In [16]:
# DF in einer neuen CSV-Datei speichern
combined_df.to_csv('data_combined.csv', index=False, encoding='utf-8-sig', sep=',')